# Generated by Django 3.0.8 on 2020-12-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_auto_20201220_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='conatact_date',
            new_name='contact_date',
        ),
    ]
